version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - aoc
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: advent_of_code
    networks:
      - aoc

networks:
  aoc:
    driver: bridge
