// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package kaggaoc

import (
	"database/sql"
)

type Completed struct {
	CompleteID int32
	UserID     sql.NullInt32
	Challenge  int32
}

type User struct {
	UserID       int32
	Username     string
	PasswordHash string
	Email        string
	Seed         string
}
